/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.mil.cet002.Swing;

import edu.mil.cet002.compraslita.Carrito;
import edu.mil.cet002.compraslita.Comercio;
import edu.mil.cet002.compraslita.Mapa;
import edu.mil.cet002.compraslita.Nodo;
import edu.mil.cet002.compraslita.Producto;
import edu.mil.cet002.compraslita.Servicios;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;

/**
 *
 * @author User
 */
public class Carro extends javax.swing.JFrame {

    private DefaultListModel<String> dlm = new DefaultListModel<>(); //Esto es la lista que contiene los productos del carrito (Sus nombres)
    private DefaultComboBoxModel<String> dlmIni = new DefaultComboBoxModel<>();
    private DefaultComboBoxModel<String> dlmFin = new DefaultComboBoxModel<>();
    private Carrito carro;
    private ResultadosBusqueda a;
    private Comercio mejorComercio;

    /**
     * Creates new form
     */
    public Carro() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null); //Centrado en pantalla

    }

    public Carro(Carrito carro, ResultadosBusqueda a) {
        this();
        this.carro = carro;
        this.a = a;
        precio.setText(calcularPrecio());
        iniciarLista();
        listaProductos.setModel(dlm);
        listaProductos.setSelectedIndex(0);
        this.setVisible(true);
        mostrarRecorrido.setEnabled(false);
        if (!carro.getListaDeProductos().isEmpty()) {
            mostrarRecorrido.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jToggleButton1 = new javax.swing.JToggleButton();
        all = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        tituloPagina = new javax.swing.JButton();
        panelCarro = new javax.swing.JPanel();
        textoCarro = new javax.swing.JTextField();
        panelItems = new javax.swing.JScrollPane();
        listaProductos = new javax.swing.JList<>();
        botonEliminar = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();
        textoTransporte = new javax.swing.JTextField();
        botonCaminar = new javax.swing.JRadioButton();
        botonAuto = new javax.swing.JRadioButton();
        panelLita = new javax.swing.JPanel();
        tituloLita = new javax.swing.JButton();
        mostrarRecorrido = new javax.swing.JButton();
        textoTotal = new javax.swing.JTextField();
        precio = new javax.swing.JTextField();
        panelUnComerio = new javax.swing.JPanel();
        botonBuscarMejorComercio = new javax.swing.JButton();
        totalMejorCom = new javax.swing.JTextField();
        mejorComNombre = new javax.swing.JTextField();
        totalMejorCom1 = new javax.swing.JTextField();
        botonRecorrerMejorComercio = new javax.swing.JButton();
        textoNombreMejorComercio = new javax.swing.JTextField();
        panelOpciones = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        comboFinal = new javax.swing.JComboBox<>();
        comboInici = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setResizable(false);
        setSize(new java.awt.Dimension(500, 450));

        all.setBackground(new java.awt.Color(255, 255, 255));
        all.setFocusable(false);
        all.setPreferredSize(new java.awt.Dimension(500, 450));

        panelTitulo.setBackground(new java.awt.Color(255, 255, 255));

        tituloPagina.setBackground(new java.awt.Color(0, 204, 153));
        tituloPagina.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tituloPagina.setForeground(new java.awt.Color(255, 255, 255));
        tituloPagina.setText("No pagué de más con Las Compras de Lita");
        tituloPagina.setBorderPainted(false);
        tituloPagina.setFocusPainted(false);
        tituloPagina.setFocusable(false);
        tituloPagina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tituloPaginaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(tituloPagina, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tituloPagina)
        );

        panelCarro.setBackground(new java.awt.Color(255, 255, 255));

        textoCarro.setEditable(false);
        textoCarro.setBackground(new java.awt.Color(255, 255, 255));
        textoCarro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textoCarro.setText("Carro de compras:");
        textoCarro.setBorder(null);
        textoCarro.setFocusable(false);

        listaProductos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        listaProductos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaProductos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaProductos.setSelectedIndex(0);
        panelItems.setViewportView(listaProductos);

        botonEliminar.setBackground(new java.awt.Color(226, 226, 226));
        botonEliminar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        botonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoswing/imagenes/elimina3.png"))); // NOI18N
        botonEliminar.setText("Quitar producto");
        botonEliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        botonVolver.setBackground(new java.awt.Color(226, 226, 226));
        botonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoswing/imagenes/volver2.png"))); // NOI18N
        botonVolver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        botonVolver.setLabel("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        textoTransporte.setEditable(false);
        textoTransporte.setBackground(new java.awt.Color(255, 255, 255));
        textoTransporte.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        textoTransporte.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textoTransporte.setText(" Medio de transporte:");
        textoTransporte.setBorder(null);
        textoTransporte.setFocusable(false);
        textoTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoTransporteActionPerformed(evt);
            }
        });

        botonCaminar.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(botonCaminar);
        botonCaminar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        botonCaminar.setText("Caminar");
        botonCaminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCaminarActionPerformed(evt);
            }
        });

        botonAuto.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(botonAuto);
        botonAuto.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        botonAuto.setSelected(true);
        botonAuto.setText("Auto");
        botonAuto.setAutoscrolls(true);

        javax.swing.GroupLayout panelCarroLayout = new javax.swing.GroupLayout(panelCarro);
        panelCarro.setLayout(panelCarroLayout);
        panelCarroLayout.setHorizontalGroup(
            panelCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCarroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCarroLayout.createSequentialGroup()
                        .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textoTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonAuto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonCaminar))
                    .addComponent(panelItems, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        panelCarroLayout.setVerticalGroup(
            panelCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCarroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelItems, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEliminar)
                    .addComponent(botonVolver)
                    .addGroup(panelCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textoTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonAuto)
                        .addComponent(botonCaminar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelLita.setBackground(new java.awt.Color(255, 255, 255));

        tituloLita.setBackground(new java.awt.Color(255, 153, 0));
        tituloLita.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tituloLita.setForeground(new java.awt.Color(255, 255, 255));
        tituloLita.setText("Modo Lita de Lazzari");
        tituloLita.setBorderPainted(false);
        tituloLita.setFocusPainted(false);
        tituloLita.setFocusable(false);
        tituloLita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tituloLitaActionPerformed(evt);
            }
        });

        mostrarRecorrido.setBackground(new java.awt.Color(255, 232, 199));
        mostrarRecorrido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoswing/imagenes/recorrido.png"))); // NOI18N
        mostrarRecorrido.setText("Iniciar Recorrido");
        mostrarRecorrido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mostrarRecorrido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarRecorridoActionPerformed(evt);
            }
        });

        textoTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textoTotal.setText("Total a pagar: $");
        textoTotal.setToolTipText("");
        textoTotal.setBorder(null);

        precio.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        precio.setBorder(null);

        javax.swing.GroupLayout panelLitaLayout = new javax.swing.GroupLayout(panelLita);
        panelLita.setLayout(panelLitaLayout);
        panelLitaLayout.setHorizontalGroup(
            panelLitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLitaLayout.createSequentialGroup()
                .addComponent(tituloLita, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mostrarRecorrido, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelLitaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLitaLayout.setVerticalGroup(
            panelLitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLitaLayout.createSequentialGroup()
                .addGroup(panelLitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mostrarRecorrido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tituloLita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelUnComerio.setBackground(new java.awt.Color(255, 255, 255));

        botonBuscarMejorComercio.setBackground(new java.awt.Color(0, 204, 153));
        botonBuscarMejorComercio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonBuscarMejorComercio.setForeground(new java.awt.Color(255, 255, 255));
        botonBuscarMejorComercio.setText("Desactivar Modo Lita -> Quiero comprar todo en el mismo comercio");
        botonBuscarMejorComercio.setAutoscrolls(true);
        botonBuscarMejorComercio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        botonBuscarMejorComercio.setBorderPainted(false);
        botonBuscarMejorComercio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarMejorComercioActionPerformed(evt);
            }
        });

        totalMejorCom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalMejorCom.setForeground(new java.awt.Color(204, 204, 204));
        totalMejorCom.setText("Comercio:");
        totalMejorCom.setToolTipText("");
        totalMejorCom.setBorder(null);

        mejorComNombre.setBorder(null);
        mejorComNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mejorComNombreActionPerformed(evt);
            }
        });

        totalMejorCom1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalMejorCom1.setForeground(new java.awt.Color(204, 204, 204));
        totalMejorCom1.setText("Total a pagar: $");
        totalMejorCom1.setToolTipText("");
        totalMejorCom1.setAutoscrolls(false);
        totalMejorCom1.setBorder(null);

        botonRecorrerMejorComercio.setBackground(new java.awt.Color(170, 236, 219));
        botonRecorrerMejorComercio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoswing/imagenes/recorrido.png"))); // NOI18N
        botonRecorrerMejorComercio.setText("Iniciar Recorrido");
        botonRecorrerMejorComercio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        botonRecorrerMejorComercio.setEnabled(false);
        botonRecorrerMejorComercio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRecorrerMejorComercioActionPerformed(evt);
            }
        });

        textoNombreMejorComercio.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        textoNombreMejorComercio.setBorder(null);
        textoNombreMejorComercio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoNombreMejorComercioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelUnComerioLayout = new javax.swing.GroupLayout(panelUnComerio);
        panelUnComerio.setLayout(panelUnComerioLayout);
        panelUnComerioLayout.setHorizontalGroup(
            panelUnComerioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUnComerioLayout.createSequentialGroup()
                .addGroup(panelUnComerioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelUnComerioLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(totalMejorCom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoNombreMejorComercio, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalMejorCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mejorComNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelUnComerioLayout.createSequentialGroup()
                        .addComponent(botonBuscarMejorComercio, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonRecorrerMejorComercio, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelUnComerioLayout.setVerticalGroup(
            panelUnComerioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUnComerioLayout.createSequentialGroup()
                .addGroup(panelUnComerioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonBuscarMejorComercio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonRecorrerMejorComercio, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelUnComerioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUnComerioLayout.createSequentialGroup()
                        .addGroup(panelUnComerioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textoNombreMejorComercio, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalMejorCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelUnComerioLayout.createSequentialGroup()
                        .addGroup(panelUnComerioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalMejorCom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mejorComNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(22, Short.MAX_VALUE))))
        );

        panelOpciones.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBorder(null);

        jTextPane1.setBorder(null);
        jTextPane1.setText("Punto final:");
        jScrollPane1.setViewportView(jTextPane1);

        comboFinal.setModel(dlmFin);

        comboInici.setModel(dlmIni);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);

        jTextPane2.setText("Punto de partida:");
        jScrollPane2.setViewportView(jTextPane2);

        javax.swing.GroupLayout panelOpcionesLayout = new javax.swing.GroupLayout(panelOpciones);
        panelOpciones.setLayout(panelOpcionesLayout);
        panelOpcionesLayout.setHorizontalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboInici, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOpcionesLayout.createSequentialGroup()
                        .addComponent(comboFinal, 0, 354, Short.MAX_VALUE)
                        .addGap(72, 72, 72))
                    .addGroup(panelOpcionesLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelOpcionesLayout.setVerticalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelOpcionesLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelOpcionesLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboInici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout allLayout = new javax.swing.GroupLayout(all);
        all.setLayout(allLayout);
        allLayout.setHorizontalGroup(
            allLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(allLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelCarro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelLita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelUnComerio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, allLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(allLayout.createSequentialGroup()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        allLayout.setVerticalGroup(
            allLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelLita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelUnComerio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(all, javax.swing.GroupLayout.PREFERRED_SIZE, 798, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(all, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tituloPaginaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tituloPaginaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloPaginaActionPerformed

    private void botonRecorrerMejorComercioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRecorrerMejorComercioActionPerformed
        try {
            a.dispose();
            Nodo origen = Servicios.getInstance().getMapa().getMapa().get(comboInici.getSelectedIndex());
            Nodo Final = Servicios.getInstance().getMapa().getMapa().get(comboFinal.getSelectedIndex());
            List<Nodo> destinoIntermedio = buscarNodoMejorComercio();
            Mapa mapa = Servicios.getInstance().getMapa();
            int camino;
            if (buttonGroup1.isSelected(botonAuto.getModel())) {
                camino = 1;
            } else {
                camino = 0;
            }
            MapaVisual m = new MapaVisual(Servicios.getInstance().calcularRecorrido(origen, Final, destinoIntermedio, mapa, camino), carro);
            m.setVisible(true);
            this.dispose();
        } catch (Exception e) {
            new PanelBusqueda().setVisible(true); // Crea y muestra panel de busqueda
            this.dispose();
        }
    }//GEN-LAST:event_botonRecorrerMejorComercioActionPerformed

    private void mejorComNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mejorComNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mejorComNombreActionPerformed

    private void textoNombreMejorComercioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoNombreMejorComercioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoNombreMejorComercioActionPerformed

    private void botonBuscarMejorComercioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarMejorComercioActionPerformed

        Comercio mejorComercio = carro.calcularCompraOptima();
        if (mejorComercio != null) {
            totalMejorCom.setForeground(Color.BLACK);
            totalMejorCom1.setForeground(Color.BLACK);
            botonRecorrerMejorComercio.setEnabled(true);
            mejorComNombre.setText(mejorComercio.getNombre());
            textoNombreMejorComercio.setText(String.valueOf(carro.getMejorPrecio()));
            this.mejorComercio = mejorComercio;
        } else {
            totalMejorCom1.setForeground(Color.BLACK);
            mejorComNombre.setText("Ningún comercio contiene todos sus productos.");
            textoNombreMejorComercio.setText(String.valueOf(""));
        }
    }//GEN-LAST:event_botonBuscarMejorComercioActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_botonVolverActionPerformed

    private void mostrarRecorridoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarRecorridoActionPerformed
        try {
            a.dispose();
            Nodo origen = Servicios.getInstance().getMapa().getMapa().get(comboInici.getSelectedIndex());
            Nodo Final = Servicios.getInstance().getMapa().getMapa().get(comboFinal.getSelectedIndex());
            List<Nodo> destinoIntermedio = convertirProductosANodos();
            Mapa mapa = Servicios.getInstance().getMapa();
            int camino;
            if (buttonGroup1.isSelected(botonAuto.getModel())) {
                camino = 1;
            } else {
                camino = 0;
            }
            MapaVisual m = new MapaVisual(Servicios.getInstance().calcularRecorrido(origen, Final, destinoIntermedio, mapa, camino), carro);
            m.setVisible(true);
            this.dispose();
        } catch (Exception e) {
            new PanelBusqueda().setVisible(true); // Crea y muestra panel de busqueda
            this.dispose();
        }
    }//GEN-LAST:event_mostrarRecorridoActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        if (!listaProductos.isSelectionEmpty()) {
            int i = listaProductos.getSelectedIndex();
            dlm.remove(i);
            carro.eliminarProducto(i);
            precio.setText(calcularPrecio());//Se actualiza el precio total del carrito
            if (!carro.getListaDeProductos().isEmpty()) {
                if (!mostrarRecorrido.isEnabled()) {
                    mostrarRecorrido.setEnabled(true);
                }
            } else {
                mostrarRecorrido.setEnabled(false);
            }
        }
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonCaminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCaminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCaminarActionPerformed

    private void textoTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoTransporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoTransporteActionPerformed

    private void tituloLitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tituloLitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloLitaActionPerformed
    private String calcularPrecio() {
        double precio = 0;
        for (int d = 0; d != carro.getListaDeProductos().size(); d++) {
            precio = precio + carro.getListaDeProductos().get(d).getPrecio();
        }

        return String.valueOf(precio);
    }

    private List<Nodo> convertirProductosANodos() {
        List<Nodo> nodos = new ArrayList();
        for (int i = 0; i < carro.getListaDeProductos().size(); i++) {
            nodos.add(carro.getListaDeProductos().get(i).getComercio().getUbicacion());
        }
        return nodos;
    }

    private List<Nodo> buscarNodoMejorComercio() {
        List<Nodo> nodos = new ArrayList();
        nodos.add(this.mejorComercio.getUbicacion());
        return nodos;
    }

    private void iniciarLista() {
        for (int i = 0; i != carro.getListaDeProductos().size(); i++) {
            dlm.addElement(carro.getListaDeProductos().get(i).getNombre() + " | " + carro.getListaDeProductos().get(i).getComercio().getNombre() + " | $" + carro.getListaDeProductos().get(i).getPrecio());
        }
        Mapa m = Servicios.getInstance().getMapa();
        for (int d = 0; d != m.getMapa().size(); d++) {
            dlmIni.addElement(m.getMapa().get(d).getNombre());
            dlmFin.addElement(m.getMapa().get(d).getNombre());
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel all;
    private javax.swing.JRadioButton botonAuto;
    private javax.swing.JButton botonBuscarMejorComercio;
    private javax.swing.JRadioButton botonCaminar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonRecorrerMejorComercio;
    private javax.swing.JButton botonVolver;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboFinal;
    private javax.swing.JComboBox<String> comboInici;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JList<String> listaProductos;
    private javax.swing.JTextField mejorComNombre;
    private javax.swing.JButton mostrarRecorrido;
    private javax.swing.JPanel panelCarro;
    private javax.swing.JScrollPane panelItems;
    private javax.swing.JPanel panelLita;
    private javax.swing.JPanel panelOpciones;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JPanel panelUnComerio;
    private javax.swing.JTextField precio;
    private javax.swing.JTextField textoCarro;
    private javax.swing.JTextField textoNombreMejorComercio;
    private javax.swing.JTextField textoTotal;
    private javax.swing.JTextField textoTransporte;
    private javax.swing.JButton tituloLita;
    private javax.swing.JButton tituloPagina;
    private javax.swing.JTextField totalMejorCom;
    private javax.swing.JTextField totalMejorCom1;
    // End of variables declaration//GEN-END:variables
}
